# Generated by Django 3.1 on 2020-08-13 14:22

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeping_beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_images',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='home_page_images',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='home_page_images',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 19, 52, 34, 144011)),
        ),
    ]
