# Generated by Django 3.1 on 2020-08-19 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeping_beds', '0002_auto_20200813_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 9, 11, 37, 172311)),
        ),
    ]
