# Generated by Django 3.1 on 2020-08-20 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeping_beds', '0003_auto_20200819_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default='NO type', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 20, 10, 26, 1, 953696)),
        ),
    ]
